SRCS=GUIConfigurationUtility.cpp \
     GUIConfigurationWizard.cpp \
     GUIControllerList.cpp \
     GUIControllerWindow.cpp \
     GUIFeatureButton.cpp \
     GUIFeatureList.cpp \

LIB=controllerwindows.a

include ../../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
