SRCS=ContentAddonDirectory.cpp \
     ContentDatabaseDirectory.cpp \
     ContentDatabaseFilter.cpp \
     ContentScanner.cpp \

LIB=content.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
