SRCS=Controller.cpp \
     ControllerFeature.cpp \
     ControllerLayout.cpp \
     ControllerTranslator.cpp \
     EasterEgg.cpp \

LIB=controllers.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))